server:
  port: 88
spring:
  application:
    name: Fng-Gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: fng-user-route
          uri: lb://Fng-User
          predicates:
            - Path=/api/**
